name: overIt
description: An app to save a complete to-do list.

version: 0.1.0

environment:
  sdk: '>=2.0.0 <3.0.0'
  # The example interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: '>=1.10.2-pre.54'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  bloc: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
    - assets/
